#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long X, std::vector<long long> S){
	long long i = 0;
	long long score = 0;
	while(i < N)
	{
		if (S[i] <= X)
			score += S[i];
		i++;
	}
	cout << score << endl;
}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
	long long N;
	std::scanf("%lld", &N);
	long long X;
	std::scanf("%lld", &X);
	std::vector<long long> S(N);
	for(int i = 0 ; i < N ; i++){
		std::scanf("%lld", &S[i]);
	}
	solve(N, X, std::move(S));
	return 0;
}
