#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long Q, std::string S, std::vector<long long> l, std::vector<long long> r){

}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
	long long N;
	std::scanf("%lld", &N);
	long long Q;
	std::scanf("%lld", &Q);
	std::string S;
	std::cin >> S;
	std::vector<long long> l(Q);
	std::vector<long long> r(Q);
	for(int i = 0 ; i < Q ; i++){
		std::scanf("%lld", &l[i]);
		std::scanf("%lld", &r[i]);
	}
	solve(N, Q, S, std::move(l), std::move(r));
	return 0;
}
