#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long M, long long L, std::vector<long long> a, std::vector<long long> b, std::vector<long long> c, std::vector<long long> d){

}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
	long long N;
	std::scanf("%lld", &N);
	long long M;
	std::scanf("%lld", &M);
	long long L;
	std::scanf("%lld", &L);
	std::vector<long long> a(N);
	for(int i = 0 ; i < N ; i++){
		std::scanf("%lld", &a[i]);
	}
	std::vector<long long> b(M);
	for(int i = 0 ; i < M ; i++){
		std::scanf("%lld", &b[i]);
	}
	std::vector<long long> c(L);
	std::vector<long long> d(L);
	for(int i = 0 ; i < L ; i++){
		std::scanf("%lld", &c[i]);
		std::scanf("%lld", &d[i]);
	}
	solve(N, M, L, std::move(a), std::move(b), std::move(c), std::move(d));
	return 0;
}
