#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
#include <climits>
using namespace std;

#define FOR(i,a,b) for(int i=a;i<=b;++i)
#define REP(i,n) FOR(i,0,n-1)


void solve(long long N, long long S, long long M, long long L){
	long long ans = LLONG_MAX;
	REP(i, 100){
		REP(j, 100){
			REP(k, 100){
				if (6*i + 8*j + 12*k >= N){
					ans = min(ans , S*i + M*j + L*k);
				}
			};
		};
	};
	cout << ans << endl;
}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
	long long N;
	std::scanf("%lld", &N);
	long long S;
	std::scanf("%lld", &S);
	long long M;
	std::scanf("%lld", &M);
	long long L;
	std::scanf("%lld", &L);
	solve(N, S, M, L);
	return 0;
}
